server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://172.20.0.4:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: ms-gateway-service
